// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "frc/smartdashboard/SmartDashboard.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/CarrigeDownCommand.h"
#include "Commands/CarrigeUpCommand.h"
#include "Commands/DriveWithJoysticks.h"
#include "Commands/GearRun.h"
#include "Commands/PuncherInCommand.h"
#include "Commands/PuncherOutCommand.h"
#include "Commands/UserClimber.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    driveController.reset(new frc::Joystick(0));
    
    lBump.reset(new frc::JoystickButton(driveController.get(), 5));
    lBump->WhileHeld(new GearRun());

    // SmartDashboard Buttons
    frc::SmartDashboard::PutData("UserClimber", new UserClimber());
    frc::SmartDashboard::PutData("DriveWithJoysticks", new DriveWithJoysticks());
    frc::SmartDashboard::PutData("CarrigeUpCommand", new CarrigeUpCommand());
    frc::SmartDashboard::PutData("CarrigeDownCommand", new CarrigeDownCommand());
    frc::SmartDashboard::PutData("GearRun", new GearRun());
    frc::SmartDashboard::PutData("PuncherInCommand", new PuncherInCommand());
    frc::SmartDashboard::PutData("PuncherOutCommand", new PuncherOutCommand());
    frc::SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<frc::Joystick> OI::getDriveController() {
   return driveController;
}

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
