// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// C++ from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


#include "OI.h"

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES
#include "frc/smartdashboard/SmartDashboard.h"
#include "Commands/ArmManual.h"
#include "Commands/ArmPos1.h"
#include "Commands/ArmPos2.h"
#include "Commands/ArmPos3.h"
#include "Commands/AutonomousCommand.h"
#include "Commands/DriveWithJoystick.h"
#include "Commands/ElevatorManual.h"
#include "Commands/ElevatorPos1.h"
#include "Commands/ElevatorPos2.h"
#include "Commands/ElevatorPos3.h"

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=INCLUDES

OI::OI() {
    // Process operator interface input here.
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    systemsController.reset(new frc::Joystick(1));
    
    l_Bump.reset(new frc::JoystickButton(systemsController.get(), 5));
    l_Bump->WhenPressed(new ArmPos3());
    l_Joy.reset(new frc::JoystickButton(systemsController.get(), 9));
    l_Joy->WhenPressed(new ArmPos2());
    r_Joy.reset(new frc::JoystickButton(systemsController.get(), 10));
    r_Joy->WhenPressed(new ArmPos1());
    y.reset(new frc::JoystickButton(systemsController.get(), 4));
    y->WhenPressed(new ElevatorPos3());
    x.reset(new frc::JoystickButton(systemsController.get(), 3));
    x->WhenPressed(new ElevatorPos2());
    a.reset(new frc::JoystickButton(systemsController.get(), 1));
    a->WhenPressed(new ElevatorPos1());
    driveController.reset(new frc::Joystick(0));
    

    // SmartDashboard Buttons
    frc::SmartDashboard::PutData("ArmPos3", new ArmPos3());
    frc::SmartDashboard::PutData("ArmPos2", new ArmPos2());
    frc::SmartDashboard::PutData("ArmPos1", new ArmPos1());
    frc::SmartDashboard::PutData("ElevatorPos3", new ElevatorPos3());
    frc::SmartDashboard::PutData("ElevatorPos2", new ElevatorPos2());
    frc::SmartDashboard::PutData("ElevatorPos1", new ElevatorPos1());
    frc::SmartDashboard::PutData("Autonomous Command", new AutonomousCommand());
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
}

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS

std::shared_ptr<frc::Joystick> OI::getDriveController() {
   return driveController;
}

std::shared_ptr<frc::Joystick> OI::getSystemsController() {
   return systemsController;
}

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
